### ISSUE TITLE
Wrong displaying in Safari

### ISSUE THREAD

**Issue by BroFox86** [pawelgrzybek/snippet-generator#1]
I have an issue with displaying your generator in Safari. Input field almost hidden. I tried to turn off all of my browser extensions but it didn't help me. See the screenshot: https://www.dropbox.com/s/iz0wp804wkjtzbb/11.png?dl=0

**Comment by pawelgrzybek** [comment]
Hi!

O damn! Its terrible, thanks for reporting. I'll fix it when I get sober enough to understand flexbox again. Thanks a lot for reporting.

Have a great day 🥑

**Comment by pawelgrzybek** [comment]
All done, thanks again for reporting @BroFox86
