### ISSUE TITLE
Atom String Interpolation

### ISSUE THREAD

**Issue by imcodingideas** [pawelgrzybek/snippet-generator#14]
I have a snippet in atom, and I can't seem to figure out how to do string interpolation i.e.  `#{name}` in a atom snippet.

```
  'flash_message':
    'prefix': 'flash'
    'body': """
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
    """
```

**Comment by pawelgrzybek** [comment]
Sorry I can't help you with this one. I don't use Atom anymore and this issue is not directly related with an app.
