### ISSUE TITLE
Tabulation as \t

### ISSUE THREAD

**Issue by davidperezgar** [pawelgrzybek/snippet-generator#15]
When the origin has a tabulation in spaces, it should translate it to vscode as \t. 

Thanks!

**Comment by rogierschouten** [comment]
@pawelgrzybek  it does NOT currently convert the tabs to spaces, when you copypaste code into the left pane., I get unescaped tabs in the copied output.

**Comment by pawelgrzybek** [comment]
Should be easy to fix.
How keen are you to submit a PR?

Thanks in advance a ton :)

**Comment by rogierschouten** [comment]
Done, #33

**Comment by alanlichen** [comment]
Any updates on this pr?

**Comment by wenfangdu** [comment]
Before that PR is merged, I've created a [VSCode extension](https://github.com/wenfangdu/vscode-snippet-generator) for this, it supports space to `\t` conversion.
