### ISSUE TITLE
Convert from one type to another

### ISSUE THREAD

**Issue by safield** [pawelgrzybek/snippet-generator#18]
It would be nice if this app could take a snippet of one format as input, and then output a snippet of the other format.

eg. Paste in a sublime snippet and output a vscode snippet.

**Comment by pranayrauthu** [comment]
@pawelgrzybek check [this](https://github.com/pawelgrzybek/snippet-generator/pull/11) pr.

**Comment by pawelgrzybek** [comment]
Hi.

It is super easy to extract info from one snippet to another using this tool but it is not the main purpose of it. It is a snippet generator not a snippet converter — good idea for another app tho :-)

Thanks for input.
