### ISSUE TITLE
Unable to select the middle part

### ISSUE THREAD

**Issue by snoopy83101** [pawelgrzybek/snippet-generator#20]
![image](https://user-images.githubusercontent.com/24613784/50470778-f3e03600-09ec-11e9-94ae-22d528fb8525.png)

Unable to select the middle part
When I need to change the middle section,
I don't want to choose all of them, but I have to start from scratch!
Why?

**Comment by pawelgrzybek** [comment]
Hi.

By default is selects everything for convenient copy / paste. If you want to edit the output simply do it in your editor. It is much more comfortable than doing that in a browser anyway.

Thanks
