### ISSUE TITLE
'\' convert error in VSCode snippet

### ISSUE THREAD

**Issue by sabertazimi** [pawelgrzybek/snippet-generator#21]
In VSCode snippet, '\' should convert to '\\' in `body` field.

**Comment by sabertazimi** [comment]
Example in [Latex-Snippets VSCode extension](https://github.com/sabertazimi/LaTeX-snippets/blob/master/snippets/snippets.json)

**Comment by pawelgrzybek** [comment]
This is a great suggestion. I will be honest with you — my RegEx skills sucks. If you don;t mind to submit PR I am more than happy to accept it. The way how it works is simple to understand and logic is abstracted per editor. There is a VSCode .js file that needs some changes in logic.

**Comment by sabertazimi** [comment]
Done in pr #22 for fixing issue #13 and issue #21
Code in pr #19 has logic error.

**Comment by sabertazimi** [comment]
Now, `${1:placeholder}` will be transformed into `\\${1:placeholder}` in vscode snippet.If you want keep to transform `${1:placeholder}` into `${1:placeholder}`, you can use `replace(/\$(?!{)/g, '\\\\$')` instead of `replace(/\$/g, '\\\\$')`.
