### ISSUE TITLE
Do the opposite operation (snippet -> "human readable")

### ISSUE THREAD

**Issue by Raphael-Duchaine** [pawelgrzybek/snippet-generator#23]
When reworking past snippets, it would be useful to be able to paste it in the IDE format to edit it without having to rewrite part of it. 

I might try to do a PR in the next few days for it.

**Comment by pawelgrzybek** [comment]
Hi.

If you need to do something like that, just invoke a snippet in IDE and then paste it to the app. I know it it generated few more steps but it keeps the app logic simple. I would like to keep it that way.

Thanks

**Comment by sweepyoface** [comment]
Doing that, you have to put all the variables in again. I don't think that's a solution.
