### ISSUE TITLE
possibility to create multiple snippets at once ?

### ISSUE THREAD

**Issue by xiaoouwang** [pawelgrzybek/snippet-generator#24]
Tks for the nice plugin ! Is it possible to enhance this great website to something like a parser working in the following way : 
the --- seperates the different code to convert to snippets

```
aaa(default description)
bbb(default trigger,prefix)
textAfter(text to convert to snippets)
---
aaaNextsnippet(default description)
bbbNextsnippet(default trigger,prefix)
textAfterNextSnippet(text to convert to snippets)
---
etc...
```

**Comment by pawelgrzybek** [comment]
Hi.

Idea is nice but `---` makes sense only to you. It is not a convention used in snippets file. The only think that `---` means to me is a `<hr>` in Markdown file.

Although it would be very simple to add this functionality, it won't be intuitive and I am not planning to add functionality like this.

Thanks for suggestion and contribution. Have a great day.

**Comment by xiaoouwang** [comment]
tks for the response ! Actually - - - is just a suggestion, it can be anything else. Buy I see what you mean, this kind of tools are used typically to add a small number of user defined snippets on top of a certain community maintained plug-in.

My case is that the language I use (Praat, a signal processing language) doesn't have any snippet available and I have to do everything from scratch so it's really impossible to to it one by one.

Can you indicate me some tutorials or avenue so that I can do it on my own? That would be really kind!
