### ISSUE TITLE
Add scope

### ISSUE THREAD

**Issue by linonetwo** [pawelgrzybek/snippet-generator#26]
```"scope": "javascript,javascriptreact,typescript,typescriptreact",```
So snippet work cross ts tsx and js jsx.

**Comment by pawelgrzybek** [comment]
Hi.

Majority of the snippets created by users are added to language specific snippets JSON file. Scope is not needed in this case. If someone creates a global snippets it is very easy to add scope manually. I may reconsider to change a base template of a VS Code snippet to:

```
"": {
  "prefix": "",
  "body": [
    ""
  ],
  "description": "",
  "scope": ""
}
```

Thanks for suggestion.

**Comment by wenfangdu** [comment]
If you're using VSCode, you can try [this extension](https://marketplace.visualstudio.com/items?itemName=wenfangdu.snippet-generator), it supports optional scope.
