### ISSUE TITLE
Escape dollar sign

### ISSUE THREAD

**Issue by jakob-fuchs** [pawelgrzybek/snippet-generator#3]
It would be a nice addition if the dollar sign ($) could be escaped automatically. This is necessary for sublime text when it is used in the actual code snippet.

```php
\$test = 'string'
```
Instead of:
```php
$test = 'string'
```

**Comment by pawelgrzybek** [comment]
Thank you for reporting an issue. Really good point! I just need to work out the regex with correct negative lookahead and I'll amend the logic for ST snippets.

**Comment by jakob-fuchs** [comment]
Thanks for adding this, but this introduced another problem.

```PHP
$test = "test";
```
Will be converted to:

```PHP
$test= "test";
``` 
It looks like any character directly following the escaped token will be removed.

**Comment by jakob-fuchs** [comment]
Sorry to bother you again, I found another related problem.

```php
$this->someMethod()
```
Gets converted to
```php
$this>someMethod()
```

**Comment by pawelgrzybek** [comment]
Uuuuups :)

**Comment by srikat** [comment]
I see that two slashes are needed to escape the $ sign.

Like this:

`\\$`

**Comment by pawelgrzybek** [comment]
I tried to review and find an issue. At this moment it works like this…

`$test = 'test'` -> `\$test = 'test'`
`$this->someMethod()` -> `\$this->someMethod()`

In my opinion the current version of regex covers majority of situation. if you can help me to find some addition edge cases please list below. For the time being I'm closing the issue.
