### ISSUE TITLE
Want to donate $ to you, but pool is closed.

### ISSUE THREAD

**Issue by cooperwalter** [pawelgrzybek/snippet-generator#32]
Hi Pawel,

Love your snippet generator! I clicked to donate to you to help you pay for the domain, but the PayPal pool is closed. I hope that means donations have covered your domain costs for the year, but I would still like to tip you. Any way I can do that? 

Cheers,
Cooper

**Comment by pawelgrzybek** [comment]
Thank you, it is very kind of you!

You are right. I collected sufficient amount of money to pay for a domain few weeks ago. I created a new PayPal pool for a domain fee in 2020. I updated links on snippet-generator.app and on README.md file.

https://paypal.me/pools/c/8fz8qLn55j

Have a lovely day and enjoy using snippet-generator 🤖
