### ISSUE TITLE
Link to copy snippets?

### ISSUE THREAD

**Issue by magicmark** [pawelgrzybek/snippet-generator#6]
Hi thanks for this!

RFC: Could I have a permalink to whatever text is typed in the box? Then I can save one link, rather than saving the individual snippets :)

Thanks!

**Comment by pawelgrzybek** [comment]
Hmmmm.

Not impossible :)
Yes you can but you need to give me some time to do it :)

Cool suggestion, thanks!

**Comment by pawelgrzybek** [comment]
Thanks for cool suggestion. It just landed :-)
